apiVersion: apps/v1
kind: Deployment
metadata:
  name: aycap-canary
spec:
  selector:
    matchLabels:
      app: aycap-canary
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aycap-canary
        env: env
        client: web
    spec:
      containers:
        - name: aycap-canary
          image: deathagility/aycap:v2
          ports:
            - containerPort: 8000
          env:
           - name: env
             value: environment
           - name: ASPNETCORE_ENVIRONMENT
             value: canary
