apiVersion: apps/v1
kind: Deployment
metadata:
  name: aycap-dev
  labels:
    app: aycap-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aycap-dev
  template:
    metadata:
      labels:
        app: aycap-dev
    spec:
      containers:
      - name: aycap-dev
        image: deathagility/aycap:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
