apiVersion: apps/v1
kind: Deployment
metadata:
  name: aycap-prod-blue
spec:
  selector:
    matchLabels:
      app: aycap-prod-blue
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aycap-prod-blue
        env: env
        client: web
    spec:
      containers:
        - name: aycap-prod-blue
          image: deathagility/aycap:v2
          ports:
            - containerPort: 8000
          env:
            - name: env
              value: environment
            - name: ASPNETCORE_ENVIRONMENT
              value: prod
