#!/usr/bin/env groovy
pipeline {
    agent any
    stages {

        stage("Deploy to MINIKUBE") {
            steps {
                script {
                    dir('./') {
                        sh "kubectl apply -f deployment.yaml"
                        sh "kubectl apply -f service.yaml"
                    }
                }
            }
        }
    }
}
