apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube
  labels:
    app: minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minikube
  template:
    metadata:
      labels:
        app: minikube
    spec:
      containers:
      - name: minikube
        image: deathagility/aycap:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
