apiVersion: v1
kind: Service
metadata:
  name: aycap-canary
spec:
  type: aycap-canary
  selector:
    app: aycap-canary
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
