apiVersion: v1
kind: Service
metadata:
  name: aycap-prod-green
spec:
  type: aycap-prod-green
  selector:
    app: aycap-prod-green
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
