apiVersion: v1
kind: Service
metadata:
  name: aycap-prod-blue
spec:
  type: aycap-prod-blue
  selector:
    app: aycap-prod-blue
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
